function [intra,extra] = classSpecPatches(imgNames,boxNames,patchSizes,filters,filterSizes,c1Space,c1Scale,c1OL)
% [intra,extra] = classSpecPatches(imgNames,boxNames,patchSizes,filters,filterSizes,c1Space,c1Scale,c1OL)

    for iImg = 1:length(imgNames)
        img = grayImage(double(imread(imgNames{iImg})));
        box = readBoxes(imgNames(iImg),boxNames(iImg));
        c1 = C1(img,filters,filterSizes,c1Space,c1Scale,c1OL);
        c1Cropped{iImg} = c1Crop(c1,box{1},'crop',c1Scale,c1Space,unique(filterSizes));
        c1Punched{iImg} = c1Crop(c1,box{1},'punch',c1Scale,c1Space,unique(filterSizes));
    end

    [intra.patches,...
     intra.bands,...
     intra.imgs,...
     intra.sizes,...
     intra.locations] = extractedPatches(c1Cropped,patchSizes);

    [extra.patches,...
     extra.bands,...
     extra.imgs,...
     extra.sizes,...
     extra.locations] = extractedPatches(c1Punched,patchSizes);
end
